// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.opencredo.roo.jpa.domain;

import org.opencredo.roo.jpa.domain.Gender;

privileged aspect Person_Roo_JavaBean {
    
    public Gender Person.getGender() {
        return this.gender;
    }
    
    public void Person.setGender(Gender gender) {
        this.gender = gender;
    }
    
}
